language: python
python:
    - "2.7"


# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda config --add channels primatelang
  - pip install --yes -r requirements_pip.txt
  - conda install --yes --file requirements.txt  
  - python setup.py install

script: make test 

